export const projects = [
  {
    id: 1,
    title: "Fresh cart",
    demo:'https://batoolaelgohary.github.io/ecommerceproject/',
    img: "./freshCart.png",
    desc: "The graduation project for Route Academy Front-End track, which is a full e commerce web application using React.js.This project’s state management was achieved using only ContextAPI to leverage its potentials to the max.A real-world payment gateway (Stripe) was implemented in this project.",
  },
  {
    id: 2,
    title: "Dashboard",
    demo:'https://dashboard-batoolelgohary.netlify.app/',
    img: "./dashboard.png",
    desc: "This project is made with react.js, typescript and scss Responsive 100% You'll need an email and password to have the authentication to view the dashboard pages, Here's the email &password Email:batool@gmail.com Password:123456",
  },
  {
    id: 3,
    title: "PC games",
    demo:'https://batoolaelgohary.github.io/Game-over/',
    img: "./pcgames.jpg",
    desc: "PC games web application crafted with HTML, CSS, Bootstrap, and pure JavaScript. Fully responsive across all screens, with real-time validation ensuring a secure and seamless experience. Explore in both dark and light modes, where every click is authenticated for logged-in access. Powered by the FreeToGame API",
  },
  {
    id: 4,
    title: "Weather check",
    demo:'https://batoolaelgohary.github.io/weatherCheck/',
    img: "weathercheck.png",
    desc: "Weather check web application created by HTML, CSS ,Bootstrap and pure javascript. You can search of any place around the world and it will show you the weather there today and two days after. ",
  },
  {
    id: 5,
    title: "Egyptian Party",
    demo:'https://batoolaelgohary.github.io/EgyptianParty/',
    img: "egyptianparty.png",
    desc: "The project was created by HTML, CSS, JavaScript and JQuery",
  },
  {
    id: 6,
    title: "Bookmarker",
    demo:'https://batoolaelgohary.github.io/bookmark/',
    img: "bookmarker.png",
    desc: "Bookmarker was created by HTML, CSS and JavaScript to Create ,Review , Update and Delete your favourite sites from and to the table , after adding the website you can click on visit button and open it.",
  },
  {
    id: 7,
    title: "Daniels",
    demo:'https://batoolaelgohary.github.io/Daniels/',
    img: "daniels.jpg",
    desc: "Daniel's portfolio was made using HTML, CSS, Bootstrap, typing animation and a little javascript for changing the color of navbar.  ",
  },
  {
    id: 8,
    title: "Devolio",
    demo:'https://batoolaelgohary.github.io/Devolio/',
    img: "devolio.jpg",
    desc: "Devolio's portfolio was made using HTML, CSS, Bootstrap, typing animation and a little javascript for changing the color of navbar.  ",
  },
  {
    id: 9,
    title: "Mealify",
    demo:'https://batoolaelgohary.github.io/mealify/',
    img: "mealify.png",
    desc: "Mealify is a web application created for resturant to view the chefs and their social media platforms ,photos of the meals and the contact information of the restuarant using HTML, CSS,font awesome icons, animation.  ",
  },
];